services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL_DEV}
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - db-dev
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    networks:
      - rmd_nest_network
    profiles:
      - dev

  db-dev:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER_DEV}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD_DEV}
      POSTGRES_DB: ${DATABASE_DB_DEV}
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    networks:
      - rmd_nest_network
    profiles:
      - dev

  pg-admin-dev:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL_DEV}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD_DEV}
    ports:
      - "5050:80"
    depends_on:
      - db-dev
    networks:
      - rmd_nest_network
    profiles:
      - dev

networks:
  rmd_nest_network:
    driver: bridge

volumes:
  db_data_dev:
