-- CreateEnum
CREATE TYPE "CONTRACT_DOWN_PAYMENT_TYPE" AS ENUM ('FULL_DOWN_PAYMENT', 'PARTIAL_DOWN_PAYMENT');

-- AlterTable
ALTER TABLE "Contract" ADD COLUMN     "downPaymentType" "CONTRACT_DOWN_PAYMENT_TYPE",
ALTER COLUMN "downPayment" DROP NOT NULL,
ALTER COLUMN "terms" DROP NOT NULL;
