-- CreateTable
CREATE TABLE "public"."ContractRequest" (
    "id" TEXT NOT NULL,
    "sqmPrice" DOUBLE PRECISION NOT NULL,
    "downPaymentType" "public"."DOWN_PAYMENT_TYPE",
    "downPaymentStatus" "public"."DOWN_PAYMENT_STATUS",
    "totalMonthlyDown" DOUBLE PRECISION,
    "totalMonthly" DOUBLE PRECISION,
    "downPayment" INTEGER,
    "totalDownPayment" DOUBLE PRECISION,
    "totalDownPaymentBalance" DOUBLE PRECISION,
    "downPaymentTerms" INTEGER,
    "terms" INTEGER,
    "miscellaneous" "public"."MISCELLANEOUS" NOT NULL,
    "miscellaneousTotal" DOUBLE PRECISION NOT NULL,
    "agentCommission" "public"."COMMISSION" NOT NULL,
    "agentCommissionTotal" DOUBLE PRECISION NOT NULL,
    "balance" DOUBLE PRECISION NOT NULL,
    "totalLotPrice" DOUBLE PRECISION NOT NULL,
    "tcp" DOUBLE PRECISION NOT NULL,
    "paymentType" "public"."PAYMENT_TYPE" NOT NULL,
    "totalCashPayment" DOUBLE PRECISION,
    "recurringPaymentDay" INTEGER,
    "nextPaymentDate" TEXT,
    "paymentStartedDate" TEXT,
    "paymentLastDate" TEXT,
    "penaltyAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "penaltyCount" INTEGER NOT NULL DEFAULT 0,
    "excessPayment" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "requestType" "public"."REQUEST_TYPE" NOT NULL,
    "status" "public"."REQUEST_STATUS" NOT NULL DEFAULT 'PENDING',
    "approvedBy" TEXT,
    "createdBy" TEXT,
    "updatedBy" TEXT,
    "deletedBy" TEXT,
    "dateCreated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dateUpdated" TIMESTAMP(3) NOT NULL,
    "dateDeleted" TIMESTAMP(3),

    CONSTRAINT "ContractRequest_pkey" PRIMARY KEY ("id")
);
